name: Build SixEyesMod
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Если майн 1.20.5+, ставь 21. Если 1.12.2, ставь 8
          distribution: 'temurin'
      - name: Fix Missing Gradle
        run: gradle wrapper
      - name: Build Mod
        run: ./gradlew build
      - name: Save Result
        uses: actions/upload-artifact@v4
        with:
          name: SixEyesMod-JAR
          path: build/libs/*.jar
          
