name: Build SixEyesMod
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Correct Gradle
        run: |
          # Устанавливаем версию 7.6, которая работает с большинством модов
          wget https://services.gradle.org
          unzip -d /opt/gradle gradle-7.6-bin.zip
          export PATH=$PATH:/opt/gradle/gradle-7.6/bin
          gradle wrapper --gradle-version 7.6
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: SixEyesMod-JAR
          path: build/libs/*.jar
          
